# Site settings
title: Bitcamp 2016
email: hello@bitca.mp
baseurl: ""
url: "http://bitca.mp"
typeform_url: "/register"
content_home_dir: "content_blocks_html"
sponsor_logo_dir: "/img/sponsor-logos"
registration_status: "closed"
